### ISSUE TITLE
BDRate report missing metrics for some clips (and also average)

### ISSUE THREAD

**Issue by urvangjoshi** [tdaede/awcy#116]
Some of the clips here didn't get any numbers (and so, no average numbers generated either): https://arewecompressedyet.com/?job=palette_withTR%402017-01-27T02%3A24%3A37.556Z&job=palette_noTR%402017-01-27T02%3A26%3A23.126Z

**Comment by tdaede** [comment]
This is because BD-Rate can't be computed for some of the videos. Try selecting the 20130119071322_Microsoft_Project_screenshot.png.y4m on your link.

It looks like "withTR" does something very bad at some quantizers (likely a desync, considering those numbers). You can try locally with the files here: https://people.xiph.org/~tdaede/sets/screenshots/

**Comment by urvangjoshi** [comment]
Ah, indeed. Sorry for the noise.
