### ISSUE TITLE
AWCY does not work well in IE browser

### ISSUE THREAD

**Issue by FangwenFu** [tdaede/awcy#65]
my ie browser information:
version: 11.0.9600.18124
Update Version: 11.0.26 (KB3104002)

**Comment by mdinger** [comment]
I don't think IE supports [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) which is used [here](https://github.com/tdaede/awcy/blob/master/www/index.html#L475-L479) and causes a parsing error. It may also be used in more locations. The fix would be to switch all `for...of` uses into `for...in` instead (though it is messier because you have to manually index everything).

The workaround is to use pretty much any browser besides IE.

**Comment by tdaede** [comment]
Nice catch! If that's all it takes then we might as well switch it (or use forEach()?). I'm currently on airport wifi so can't download the IE11 test VM to check, though...

**Comment by mdinger** [comment]
Maybe you already checked but this now works in IE. So https://github.com/tdaede/awcy/pull/66 fixed it.

**Comment by tdaede** [comment]
Indeed, I finally got my IE11 VM working. Thanks.
